main: dk.muj.derius.excavation.DeriusExcavation
name: Derius-Excavation
version: 0.2_dev
#website: http://muj.dk/Derius
authors: [Madus, Ulumulu1510]
description: §eExcavation
depend: [Derius-Core]
load: startup
